version: '2'
services:
  cmsboaweb-app:
    image: cmsboaweb
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.132.71.184:5432/ccboawebdb
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8083:8083
  cmsboaweb-postgresql:
    extends:
      file: postgresql.yml
      service: cmsboaweb-postgresql
